### ISSUE TITLE
Cannot edit Device because of empty device name

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_pricing#317]
Cannot edit (and click) on a device due to empty device name.
Cannot find a form (i.e. in Ralph_assets) where the name should be obligatory

![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/4752194/752b8550-5aa8-11e4-815c-b2d35bf7fb6f.JPG)

**Comment by mkurek** [comment]
Name is not obligatory for asset (actually asset has no name and we take paired device hostname as asset name). But anyway django allows you to click on row with empty name - just try click near left border of this cell.
