### ISSUE TITLE
Usage types: Value rounding: Not rounding

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_pricing#352]
Despite setting Value rounding: 'Decimal places = 2', when they are ending with '0' i.e. 10, 20, 50, they are shown as 1, 2, 5. 
Examples:
47.50 is shown as 47.5
34.80 is shown as 34.8
etc
![reseda_captcha](https://cloud.githubusercontent.com/assets/9283029/5577053/44ba5496-9009-11e4-871c-2e221c3341b1.JPG)

**Comment by damian1976** [comment]
This issue us related to PR: https://github.com/allegro/ralph_pricing/pull/417. When it's closed this issue can be closed too.

**Comment by mkurek** [comment]
PR #417 was merged. issue closed.
