### ISSUE TITLE
Monthly costs: Calculation fails for some date(s)

### ISSUE THREAD

**Issue by damian1976** [allegro/ralph_pricing#369]
This is just a kind request to add a tip (hint) when moving a mouse on X (next to some date),
when VerifiedDailyCostsExistsError raises, explaining the reason (i.e. "Cost for given date has been already accepted")
![reseda_capture](https://cloud.githubusercontent.com/assets/9283029/5855307/13c5fa12-a237-11e4-9c56-adf341e11a4d.JPG)

**Comment by mkurek** [comment]
This will be resolved as part of https://github.com/allegro/ralph_pricing/issues/444
